version: 2
updates:
  - package-ecosystem: "npm"
    labels:
      - "npm dependencies"
    commit-message:
      prefix: "chore"
    target-branch: "development"
    directory: "/"
    open-pull-requests-limit: 10
    reviewers:
      - "michalfedyna"
    schedule:
      interval: "daily"
