workflows:
  ios-e2e-workflow:
    name: iOS E2E Workflow
    max_build_duration: 10
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install tools
        script: |
          brew tap wix/brew
          brew install applesimutils
          npm install -g detox-cli
      - name: Install dependencies
        script: npm run install:all
      - name: Run build
        script: npm run test:e2e:build:ios:release
      - name: Run e2e tests
        script: npm run test:e2e:ios:release

