export type {
  FunctionComponent,
  FunctionComponentWithChildren,
  SVGComponent,
  MarginProps,
  PaddingProps,
  SpacingProps,
  AlignProps,
  ViewProps,
  BackgroundProps,
  FontProps,
  TranslationProps,
  SizeProps,
  BorderProps,
  SVGProps,
} from './types';
