name: Main

on:
  push:
    branches: [development]
  pull_request:
    branches: ['**']

jobs:
  tests:
    name: Run app tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Run performance testing script
        run: ./reassure-tests.sh

      - name: Run Danger.js
        run: npm run ci:danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
