name: Main

on:
  push:
    branches: [development]
  pull_request:
    branches: ['**']

jobs:
  perf-tests:
    name: Run performance tests
    runs-on: ubuntu-latest
    steps:
      - name: Run performance testing script
        run: ./reassure-tests.sh

      - name: Run Danger.js
        run: npm run ci:danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
