name: Main Workflow

on:
  push:
    branches: [development]
  pull_request:
    branches: ['**']

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.4.0

      - name: Run Eslint
        run: npm run ci:lint

      - name: Run Typescript check
        run: npm run ci:tsc

  performance-tests:
    name: Run performance regression tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.4.0

      - name: Run performance testing script
        run: ./reassure-tests.sh

      - name: Run Danger.js
        run: npm run ci:danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive performance regression tests
        uses: actions/upload-artifact@v3
        with:
          name: performance-regression
          path: ./.reassure/output.md

